context: |
  objects = [red block, blue block, green bowl, blue bowl, yellow block, green block]
  # put two blocks into the green bowl
  pick_and_place(red block, green bowl)
  pick_and_place(yellow block, green bowl)
  done()
command:
  "# put a block and a bowl into the green bowl"
options:
  - text: pick_and_place(blue block, green bowl)
    affordance: 1.0
  - text: pick_and_place(green block, green bowl)
    affordance: 1.0
  - text: pick_and_place(blue bowl, green bowl)
    affordance: 1.0
termination_string:
  done()
max_steps: 5
